networks:
  nginx:
    external: true


services:
  ###################################
  ######## LOGROTATE & CRON #########
  ###################################

  logrotate:
    container_name: 'logrotate'
    build:
      context: logrotate/
      dockerfile: Dockerfile
      target: development
    image: logrotate:development
    working_dir: /var/log/docker-services/
    restart: unless-stopped
    volumes:
      - ${PATH_PROJECTS_LOGS}/:/var/log/docker-services/
    networks:
      - nginx